// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';


console.log("Reason!");

var x = ( 'here is  a string from JS.' );

console.log(x + " back in Reason land");

exports.x = x;
/*  Not a pure module */
